### ISSUE TITLE
text endpoint for list of members

### ISSUE THREAD

**Issue by lizzyaustad** [elixirlabsinc/pangeanetwork#15]
An officer user should be able to send a text to our shortcode with keyword "MEMBERS" and receive a text back with a list of all of the members within their co-op and each of their member ids

This should also validate that the user the text is received from has the "officer" role and if not, send back an error message

**Comment by OmarSyed** [comment]
Hey Lizzy, I could work on this issue

**Comment by lizzyaustad** [comment]
great! be sure to pull the latest master and feel free to let me know if you have any questions.

**Comment by OmarSyed** [comment]
Sounds great, thanks!
